## Importing the library

In [1]:
import numpy as np

## Creating a numpy array

#### (1) Array containing zeros

In [2]:
length=10
zeros=np.zeros(length)

In [3]:
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### (2) Array containing ones

In [4]:
length=10
ones=np.ones(length)

In [5]:
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### (3) Array with fixed starting point, ending point and fixed number of points:

In [6]:
length=10
starting_point=1
ending_point=10
array=np.linspace(starting_point,ending_point,length)

In [7]:
print(array)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
#You can simply write it as:
array=np.linspace(1,10,10)
print(array)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### (4) Array with fixed starting point, ending point and fixed spacing:

In [9]:
spacing=0.5
starting_point=1
ending_point=5
array=np.arange(starting_point,ending_point,spacing)
print(array)
#Note this function creates array with its last element less than the ending point.

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [10]:
#You can simply write it as:
array=np.arange(1,5,0.5)
print(array)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


#### (5) Array with self defined data points:

In [11]:
array=np.array([1,4,5,8,3])
print(array)

[1 4 5 8 3]


## Elements in an array

#### Finding out the length of the array:

In [12]:
array=np.array([1,4,5,8,3])
length=len(array)
print('Length of the array is : ',length)

Length of the array is :  5


#### Extracting an element from the array

In [13]:
array=np.array([1,4,5,8,3])

#Note indexing in python starts with 0 and ends with length of array -1

first_element=array[0]
last_element=array[len(array)-1]

print('first element : ',first_element)
print('last element : ',last_element)

first element :  1
last element :  3


#### Finding index of element

In [14]:
array=np.array([1,4,5,8,3,6,8,9,5,3])
element=5

print(np.where(array==5))

#Note as 5 occurs twice it gives the index of both the occurances
# == is equal to operator in python

(array([2, 8], dtype=int64),)


#### Slicing an array

In [15]:
array=np.array([1,4,5,8,3,6,8,9,5,3])
first_index=1
last_index=4

print(array[first_index:last_index])

#Note it prints elements from index 1 and before index 4

[4 5 8]


#### Counting occurance of any condition

In [16]:
array=np.array([1,4,5,8,3,6,8,9,5,3])

print(np.count_nonzero(array>4))

#Note it prints the number of elements greater than 4


6


#### Sorting an array:

In [17]:
array=np.array([1,4,5,8,3,6,8,9,5,3])
print('Sorted array : ',np.sort(array))

Sorted array :  [1 3 3 4 5 5 6 8 8 9]


## Creating a matrix in numpy

#### (1) Matrix containing zeros

In [18]:
matrix=np.zeros((2,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


#### (2) Matrix containing ones

In [19]:
matrix=np.ones((2,2))
print(matrix)

[[1. 1.]
 [1. 1.]]


#### (3) Matrix containing self defined data points

In [20]:
matrix=np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


## Operations on matrix

#### Finding shape of the numpy array

In [21]:
array=np.array([1,4,5,8,3,6,8,9,5,3])
matrix=np.array([[1,2],[3,4]])

print('Shape of array : ',np.shape(array))
print('Shape of matrix : ',np.shape(matrix))

Shape of array :  (10,)
Shape of matrix :  (2, 2)


#### Reshaping a matrix

In [22]:
matrix=np.array([[1,2,3],[5,4,6]])

print('Matrix before reshaping')
print(matrix)

print('Matrix after reshaping')
print(np.reshape(matrix,(3,2)))

Matrix before reshaping
[[1 2 3]
 [5 4 6]]
Matrix after reshaping
[[1 2]
 [3 5]
 [4 6]]


## Some mathematical operations on arrays

In [23]:
array=np.array([1,4,5,8,3,6,8,9,5,3])

#Sum of all elements
print('Sum : ',np.sum(array))

#Mean of all elements
print('Mean : ',np.mean(array))

Sum :  52
Mean :  5.2


## Some mathematical operations on matrices

In [24]:
matrix=np.array([[1,2],[5,4]])

#Determinent of the matrix
print('Determinent : ',np.linalg.det(matrix))

#Inverse of the matrix
print('Inverse')
print(np.linalg.inv(matrix))

Determinent :  -6.0
Inverse
[[-0.66666667  0.33333333]
 [ 0.83333333 -0.16666667]]


#### There are a lot of interesting numpy functions like finding fourier transform, sine, cosine of arrays. It solves a lot of linear algebra problems

To view click 
<a href="https://numpy.org/doc/stable/reference/">Learn more about Numpy</a>
